name: Build

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Determine Release Version
      id: set-version
      if: startsWith(github.ref, 'refs/heads/release/')
      run: |
        RELEASE_VERSION=$(echo "${GITHUB_REF#refs/heads/release/}")
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
        echo "Release version detected: ${RELEASE_VERSION}"

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        overwrite-settings: true

    - name: Check GPG
      run: |
        gpg --list-secret-keys
        cat ~/.m2/settings.xml

    - name: Build with Maven
      run: mvn -B clean package verify deploy -Drevision=${{ env.RELEASE_VERSION }} --file pom.xml
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
